version: '3.8'
services: 
  app: 
    build: . # 先找同级目录的 Dockerfile，构建一个镜像出来
    ports: 
      - "3000:3000"
    depends_on: 
      - db
    environment: 
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_DATABASE=test
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
  db: 
    container_name: db
    image: mysql:8
    environment: 
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=test
    ports:
      - 3307:3306
    volumes:
      - /Users/lijiahao/Documents/docker-data/mysql:/var/lib/mysql